theme: 
  - osuny
  - osuny-plugin-centered-layout
  - osuny-plugin-centered-footer
_merge: deep
params:
  breadcrumb:
    position: none
  summary:
    position: content
  search:
    active: true
  logo:
    header: '/assets/images/bulle.svg'
    footer: '/assets/images/logo.svg'
  home:
    head:
      title: site
  posts:
    index:
      layout: grid
    single:
      options:
        authors: false
        published_at: true
        reading_time: true
        signature: true
        updated_at: false
