[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/about/index.html"
to = "/a-propos/"

[[redirects]]
from = "/actualites/2026-01-20-tiktok-n-est-pas-matlab/index.html"
to = "/actualites/2026-01-20-tiktok-nest-pas-matlab-le-profilage-algorithmique-n-est-ni-de-l-education-ni-de-l-emancipation-8b82a/"

[[redirects]]
from = "/actualites/2026-01-20-tiktok-n-est-pas-matlab-le-profilage-algorithmique-n-est-ni-de-l-education-ni-de-l-emancipation/index.html"
to = "/actualites/2026-01-20-tiktok-nest-pas-matlab-le-profilage-algorithmique-n-est-ni-de-l-education-ni-de-l-emancipation-8b82a/"

[[redirects]]
from = "/actualites/2024-03-26-numerique-ethique-en-entreprise-levier-de-changement-ou-concert-de-pipeau-1/index.html"
to = "/actualites/2026-03-26-numerique-ethique-en-entreprise-levier-de-changement-ou-concert-de-pipeau-1/"

